const Craziness = [
    "Why didn’t the twin towers ever get along? They had too many clashes! ✈️",
    "9/11 jokes don’t land well—but planes do. 😬💔",
    "Making jokes about 9/11 is like playing with fire—it’s bound to crash and burn. 🔥",
    "Why did the office workers never take the elevator on 9/11? They couldn’t trust it to hold up. 😅💼",
    "Terrorists told the pilot to take a seat. He replied, ‘I’ll pass.’ 😐🛫",
    "9/11 was the only time the office had a quick exit strategy. 😳🏢",
    "Making light of 9/11 is like poking a hornet’s nest—it always stings. 🕊️",
    "Comedy about 9/11 is a high-risk performance—many don’t make it out alive. 🎭",
    "What’s a 9/11 joke’s shelf life? Hopefully shorter than the towers’ fall. ⏳",
    "The best way to avoid 9/11 jokes? Just tower above them. 🛑",
    "When does a skeleton laugh? When someone tickles his funny bone!",
    "Why don't skeletons fight each other? They don't have the guts",
    "What do skeletons hate the most about wind? Nothing, it goes right through them.",
    "But first, let me take a Skelfie",
    "Why are graveyards so noisy? Because of all the coffin!",
    "How did I know where you would go next? Oh I felt it in my bones!",
    "What? A telephone? Nah, I'm using a telebone.",
    "These aren't all of them. I've got a skeleTON more!",
    "Papyrus stood by the fire for too long. Now he's BONE-dry! What a bonehead....",
    "I'm not fat. I'm just big boned!",
    "I'm so lazy, I'm bone idle!",
    "What do skeletons say before they begin dining? Bone-Appetit!",
    "That annoying dog came back and stole more of our bones. He even ran off with Papyrus' left leg! You could say he didn't leave him with a leg to stand on!",
    "What do you call a skeleton snake? A rattler!",
    "Have you seen my brother? I have a BONE to pick with him.",
    "What did the skeleton say while riding his Harley Davidson motorcycle? I’m bone to be wild!",
    "My brother always works himself down to the bone!",
    "Why did the skeleton want a friend? Because she was feeling bonely",
    "What does a skeleton tile his roof with? Shin-gles!",
    "What do you do if you see a skeleton running across a road? Jump out of your skin and join him!",
    "Papyrus' date didn't go well, did it? Yeah, He only loves every bone in your body....",
    "Everytime I hear a skeleton joke I feel it in my bones",
    "Skulls are always single because they have no body",
    "Man, these jokes aren't even that humerus.",
    "These jokes are very bare bones",
    "Oh hey, you know that Papyrus once had a dream about his car bed. You could say it was a very AUTO-BODY Experience.",
    "My brother rides a motorcycle now! He's bad to the BONE.",
    "Why do skeletons make bad miners? Because they only go 6 FOOT UNDER GROUND",
    "You wanna know why skeletons are terrible liars? Everyone can see right through them!",
    "What's Papyrus's favorite music video? Spooky Scary Skeletons!",
    "Did ya hear the one about the baby skeleton? He liked to rattle his bones.",
    "A dog stole a skeleton's left leg and left arm the other day. But it's cool he's ALL RIGHT now!",
    "What d'ye call a monkey with no skin? A babBONE!",
    "I don't know if I should put a little more BACKBONE into these jokes, but then again it is TIBIA expected that I'll get lazy and not try as hard to make a skele-TON of them... Dang... I'm such a BONEHEAD.",
    "I asked my brother the instrument one and he replied 'Bonegos'.",
    "The dancing Sans seem to really be in skele-tune with the music.",
    "What happens with a skeleton on e621? He gets a boner!",

    "if a black guy and a jew jumped off a building who will hit the ground first?.... the black guy because chains are heavier than ash",
    "Why didn’t the twin towers ever get along? They had too many clashes! ✈️",
    "9/11 jokes don’t land well—but planes do. 😬💔",
    "Making jokes about 9/11 is like playing with fire—it’s bound to crash and burn. 🔥",
    "Why did the office workers never take the elevator on 9/11? They couldn’t trust it to hold up. 😅💼",
    "Terrorists told the pilot to take a seat. He replied, ‘I’ll pass.’ 😐🛫",
    "9/11 was the only time the office had a quick exit strategy. 😳🏢",
    "Making light of 9/11 is like poking a hornet’s nest—it always stings. 🕊️",
    "Comedy about 9/11 is a high-risk performance—many don’t make it out alive. 🎭",
    "What’s a 9/11 joke’s shelf life? Hopefully shorter than the towers’ fall. ⏳",
    "The best way to avoid 9/11 jokes? Just tower above them. 🛑",
    "When does a skeleton laugh? When someone tickles his funny bone!",
    "Why don't skeletons fight each other? They don't have the guts",
    "What do skeletons hate the most about wind? Nothing, it goes right through them.",
    "But first, let me take a Skelfie",
    "Why are graveyards so noisy? Because of all the coffin!",
    "How did I know where you would go next? Oh I felt it in my bones!",
    "What? A telephone? Nah, I'm using a telebone.",
    "These aren't all of them. I've got a skeleTON more!",
    "Papyrus stood by the fire for too long. Now he's BONE-dry! What a bonehead....",
    "I'm not fat. I'm just big boned!",
    "I'm so lazy, I'm bone idle!",
    "What do skeletons say before they begin dining? Bone-Appetit!",
    "That annoying dog came back and stole more of our bones. He even ran off with Papyrus' left leg! You could say he didn't leave him with a leg to stand on!",
    "What do you call a skeleton snake? A rattler!",
    "Have you seen my brother? I have a BONE to pick with him.",
    "What did the skeleton say while riding his Harley Davidson motorcycle? I’m bone to be wild!",
    "My brother always works himself down to the bone!",
    "Why did the skeleton want a friend? Because she was feeling bonely",
    "What does a skeleton tile his roof with? Shin-gles!",
    "What do you do if you see a skeleton running across a road? Jump out of your skin and join him!",
    "Papyrus' date didn't go well, did it? Yeah, He only loves every bone in your body....",
    "Everytime I hear a skeleton joke I feel it in my bones",
    "Skulls are always single because they have no body",
    "Man, these jokes aren't even that humerus.",
    "These jokes are very bare bones",
    "Oh hey, you know that Papyrus once had a dream about his car bed. You could say it was a very AUTO-BODY Experience.",
    "My brother rides a motorcycle now! He's bad to the BONE.",
    "Why do skeletons make bad miners? Because they only go 6 FOOT UNDER GROUND",
    "You wanna know why skeletons are terrible liars? Everyone can see right through them!",
    "What's Papyrus's favorite music video? Spooky Scary Skeletons!",
    "Did ya hear the one about the baby skeleton? He liked to rattle his bones.",
    "A dog stole a skeleton's left leg and left arm the other day. But it's cool he's ALL RIGHT now!",
    "What d'ye call a monkey with no skin? A babBONE!",
    "I don't know if I should put a little more BACKBONE into these jokes, but then again it is TIBIA expected that I'll get lazy and not try as hard to make a skele-TON of them... Dang... I'm such a BONEHEAD.",
    "I asked my brother the instrument one and he replied 'Bonegos'.",
    "The dancing Sans seem to really be in skele-tune with the music.",
    "What happens with a skeleton on e621? He gets a boner!",

    "if a black guy and a jew jumped off a building who will hit the ground first?.... the black guy because chains are heavier than ash",
    "Why didn’t the twin towers ever get along? They had too many clashes! ✈️",
    "9/11 jokes don’t land well—but planes do. 😬💔",
    "Making jokes about 9/11 is like playing with fire—it’s bound to crash and burn. 🔥",
    "Why did the office workers never take the elevator on 9/11? They couldn’t trust it to hold up. 😅💼",
    "Terrorists told the pilot to take a seat. He replied, ‘I’ll pass.’ 😐🛫",
    "9/11 was the only time the office had a quick exit strategy. 😳🏢",
    "Making light of 9/11 is like poking a hornet’s nest—it always stings. 🕊️",
    "Comedy about 9/11 is a high-risk performance—many don’t make it out alive. 🎭",
    "What’s a 9/11 joke’s shelf life? Hopefully shorter than the towers’ fall. ⏳",
    "The best way to avoid 9/11 jokes? Just tower above them. 🛑",
    "When does a skeleton laugh? When someone tickles his funny bone!",
    "Why don't skeletons fight each other? They don't have the guts",
    "What do skeletons hate the most about wind? Nothing, it goes right through them.",
    "But first, let me take a Skelfie",
    "Why are graveyards so noisy? Because of all the coffin!",
    "How did I know where you would go next? Oh I felt it in my bones!",
    "What? A telephone? Nah, I'm using a telebone.",
    "These aren't all of them. I've got a skeleTON more!",
    "Papyrus stood by the fire for too long. Now he's BONE-dry! What a bonehead....",
    "I'm not fat. I'm just big boned!",
    "I'm so lazy, I'm bone idle!",
    "What do skeletons say before they begin dining? Bone-Appetit!",
    "That annoying dog came back and stole more of our bones. He even ran off with Papyrus' left leg! You could say he didn't leave him with a leg to stand on!",
    "What do you call a skeleton snake? A rattler!",
    "Have you seen my brother? I have a BONE to pick with him.",
    "What did the skeleton say while riding his Harley Davidson motorcycle? I’m bone to be wild!",
    "My brother always works himself down to the bone!",
    "Why did the skeleton want a friend? Because she was feeling bonely",
    "What does a skeleton tile his roof with? Shin-gles!",
    "What do you do if you see a skeleton running across a road? Jump out of your skin and join him!",
    "Papyrus' date didn't go well, did it? Yeah, He only loves every bone in your body....",
    "Everytime I hear a skeleton joke I feel it in my bones",
    "Skulls are always single because they have no body",
    "Man, these jokes aren't even that humerus.",
    "These jokes are very bare bones",
    "Oh hey, you know that Papyrus once had a dream about his car bed. You could say it was a very AUTO-BODY Experience.",
    "My brother rides a motorcycle now! He's bad to the BONE.",
    "Why do skeletons make bad miners? Because they only go 6 FOOT UNDER GROUND",
    "You wanna know why skeletons are terrible liars? Everyone can see right through them!",
    "What's Papyrus's favorite music video? Spooky Scary Skeletons!",
    "Did ya hear the one about the baby skeleton? He liked to rattle his bones.",
    "A dog stole a skeleton's left leg and left arm the other day. But it's cool he's ALL RIGHT now!",
    "What d'ye call a monkey with no skin? A babBONE!",
    "I don't know if I should put a little more BACKBONE into these jokes, but then again it is TIBIA expected that I'll get lazy and not try as hard to make a skele-TON of them... Dang... I'm such a BONEHEAD.",
    "I asked my brother the instrument one and he replied 'Bonegos'.",
    "The dancing Sans seem to really be in skele-tune with the music.",
    "What happens with a skeleton on e621? He gets a boner!",

    "if a black guy and a jew jumped off a building who will hit the ground first?.... the black guy because chains are heavier than ash",
    "Why didn’t the twin towers ever get along? They had too many clashes! ✈️",
    "9/11 jokes don’t land well—but planes do. 😬💔",
    "Making jokes about 9/11 is like playing with fire—it’s bound to crash and burn. 🔥",
    "Why did the office workers never take the elevator on 9/11? They couldn’t trust it to hold up. 😅💼",
    "Terrorists told the pilot to take a seat. He replied, ‘I’ll pass.’ 😐🛫",
    "9/11 was the only time the office had a quick exit strategy. 😳🏢",
    "Making light of 9/11 is like poking a hornet’s nest—it always stings. 🕊️",
    "Comedy about 9/11 is a high-risk performance—many don’t make it out alive. 🎭",
    "What’s a 9/11 joke’s shelf life? Hopefully shorter than the towers’ fall. ⏳",
    "The best way to avoid 9/11 jokes? Just tower above them. 🛑",
    "When does a skeleton laugh? When someone tickles his funny bone!",
    "Why don't skeletons fight each other? They don't have the guts",
    "What do skeletons hate the most about wind? Nothing, it goes right through them.",
    "But first, let me take a Skelfie",
    "Why are graveyards so noisy? Because of all the coffin!",
    "How did I know where you would go next? Oh I felt it in my bones!",
    "What? A telephone? Nah, I'm using a telebone.",
    "These aren't all of them. I've got a skeleTON more!",
    "Papyrus stood by the fire for too long. Now he's BONE-dry! What a bonehead....",
    "I'm not fat. I'm just big boned!",
    "I'm so lazy, I'm bone idle!",
    "What do skeletons say before they begin dining? Bone-Appetit!",
    "That annoying dog came back and stole more of our bones. He even ran off with Papyrus' left leg! You could say he didn't leave him with a leg to stand on!",
    "What do you call a skeleton snake? A rattler!",
    "Have you seen my brother? I have a BONE to pick with him.",
    "What did the skeleton say while riding his Harley Davidson motorcycle? I’m bone to be wild!",
    "My brother always works himself down to the bone!",
    "Why did the skeleton want a friend? Because she was feeling bonely",
    "What does a skeleton tile his roof with? Shin-gles!",
    "What do you do if you see a skeleton running across a road? Jump out of your skin and join him!",
    "Papyrus' date didn't go well, did it? Yeah, He only loves every bone in your body....",
    "Everytime I hear a skeleton joke I feel it in my bones",
    "Skulls are always single because they have no body",
    "Man, these jokes aren't even that humerus.",
    "These jokes are very bare bones",
    "Oh hey, you know that Papyrus once had a dream about his car bed. You could say it was a very AUTO-BODY Experience.",
    "My brother rides a motorcycle now! He's bad to the BONE.",
    "Why do skeletons make bad miners? Because they only go 6 FOOT UNDER GROUND",
    "You wanna know why skeletons are terrible liars? Everyone can see right through them!",
    "What's Papyrus's favorite music video? Spooky Scary Skeletons!",
    "Did ya hear the one about the baby skeleton? He liked to rattle his bones.",
    "A dog stole a skeleton's left leg and left arm the other day. But it's cool he's ALL RIGHT now!",
    "What d'ye call a monkey with no skin? A babBONE!",
    "I don't know if I should put a little more BACKBONE into these jokes, but then again it is TIBIA expected that I'll get lazy and not try as hard to make a skele-TON of them... Dang... I'm such a BONEHEAD.",
    "I asked my brother the instrument one and he replied 'Bonegos'.",
    "The dancing Sans seem to really be in skele-tune with the music.",
    "What happens with a skeleton on e621? He gets a boner!",

    "if a black guy and a jew jumped off a building who will hit the ground first?.... the black guy because chains are heavier than ash",
    "Why didn’t the twin towers ever get along? They had too many clashes! ✈️",
    "9/11 jokes don’t land well—but planes do. 😬💔",
    "Making jokes about 9/11 is like playing with fire—it’s bound to crash and burn. 🔥",
    "Why did the office workers never take the elevator on 9/11? They couldn’t trust it to hold up. 😅💼",
    "Terrorists told the pilot to take a seat. He replied, ‘I’ll pass.’ 😐🛫",
    "9/11 was the only time the office had a quick exit strategy. 😳🏢",
    "Making light of 9/11 is like poking a hornet’s nest—it always stings. 🕊️",
    "Comedy about 9/11 is a high-risk performance—many don’t make it out alive. 🎭",
    "What’s a 9/11 joke’s shelf life? Hopefully shorter than the towers’ fall. ⏳",
    "The best way to avoid 9/11 jokes? Just tower above them. 🛑",
    "When does a skeleton laugh? When someone tickles his funny bone!",
    "Why don't skeletons fight each other? They don't have the guts",
    "What do skeletons hate the most about wind? Nothing, it goes right through them.",
    "But first, let me take a Skelfie",
    "Why are graveyards so noisy? Because of all the coffin!",
    "How did I know where you would go next? Oh I felt it in my bones!",
    "What? A telephone? Nah, I'm using a telebone.",
    "These aren't all of them. I've got a skeleTON more!",
    "Papyrus stood by the fire for too long. Now he's BONE-dry! What a bonehead....",
    "I'm not fat. I'm just big boned!",
    "I'm so lazy, I'm bone idle!",
    "What do skeletons say before they begin dining? Bone-Appetit!",
    "That annoying dog came back and stole more of our bones. He even ran off with Papyrus' left leg! You could say he didn't leave him with a leg to stand on!",
    "What do you call a skeleton snake? A rattler!",
    "Have you seen my brother? I have a BONE to pick with him.",
    "What did the skeleton say while riding his Harley Davidson motorcycle? I’m bone to be wild!",
    "My brother always works himself down to the bone!",
    "Why did the skeleton want a friend? Because she was feeling bonely",
    "What does a skeleton tile his roof with? Shin-gles!",
    "What do you do if you see a skeleton running across a road? Jump out of your skin and join him!",
    "Papyrus' date didn't go well, did it? Yeah, He only loves every bone in your body....",
    "Everytime I hear a skeleton joke I feel it in my bones",
    "Skulls are always single because they have no body",
    "Man, these jokes aren't even that humerus.",
    "I don't know if I should put a little more BACKBONE into these jokes, but then again it is TIBIA expected that I'll get lazy and not try as hard to make a skele-TON of them... Dang... I'm such a BONEHEAD.",
    "These jokes are very bare bones",
    "Oh hey, you know that Papyrus once had a dream about his car bed. You could say it was a very AUTO-BODY Experience.",
    "My brother rides a motorcycle now! He's bad to the BONE.",
    "Why do skeletons make bad miners? Because they only go 6 FOOT UNDER GROUND",
    "You wanna know why skeletons are terrible liars? Everyone can see right through them!",
    "What's Papyrus's favorite music video? Spooky Scary Skeletons!",
    "Did ya hear the one about the baby skeleton? He liked to rattle his bones.",
    "A dog stole a skeleton's left leg and left arm the other day. But it's cool he's ALL RIGHT now!",
    "What d'ye call a monkey with no skin? A babBONE!",
    "I asked my brother the instrument one and he replied 'Bonegos'.",
    "The dancing Sans seem to really be in skele-tune with the music.",
    "What happens with a skeleton on e621? He gets a boner!",

    "if a black guy and a jew jumped off a building who will hit the ground first?.... the black guy because chains are heavier than ash",
    "Why didn’t the twin towers ever get along? They had too many clashes! ✈️",
    "9/11 jokes don’t land well—but planes do. 😬💔",
    "Making jokes about 9/11 is like playing with fire—it’s bound to crash and burn. 🔥",
    "Why did the office workers never take the elevator on 9/11? They couldn’t trust it to hold up. 😅💼",
    "Terrorists told the pilot to take a seat. He replied, ‘I’ll pass.’ 😐🛫",
    "9/11 was the only time the office had a quick exit strategy. 😳🏢",
    "Making light of 9/11 is like poking a hornet’s nest—it always stings. 🕊️",
    "Comedy about 9/11 is a high-risk performance—many don’t make it out alive. 🎭",
    "What’s a 9/11 joke’s shelf life? Hopefully shorter than the towers’ fall. ⏳",
    "The best way to avoid 9/11 jokes? Just tower above them. 🛑",
    "When does a skeleton laugh? When someone tickles his funny bone!",
    "Why don't skeletons fight each other? They don't have the guts",
    "What do skeletons hate the most about wind? Nothing, it goes right through them.",
    "But first, let me take a Skelfie",
    "Why are graveyards so noisy? Because of all the coffin!",
    "How did I know where you would go next? Oh I felt it in my bones!",
    "What? A telephone? Nah, I'm using a telebone.",
    "These aren't all of them. I've got a skeleTON more!",
    "Papyrus stood by the fire for too long. Now he's BONE-dry! What a bonehead....",
    "I'm not fat. I'm just big boned!",
    "I'm so lazy, I'm bone idle!",
    "What do skeletons say before they begin dining? Bone-Appetit!",
    "That annoying dog came back and stole more of our bones. He even ran off with Papyrus' left leg! You could say he didn't leave him with a leg to stand on!",
    "What do you call a skeleton snake? A rattler!",
    "Have you seen my brother? I have a BONE to pick with him.",
    "What did the skeleton say while riding his Harley Davidson motorcycle? I’m bone to be wild!",
    "My brother always works himself down to the bone!",
    "Why did the skeleton want a friend? Because she was feeling bonely",
    "What does a skeleton tile his roof with? Shin-gles!",
    "What do you do if you see a skeleton running across a road? Jump out of your skin and join him!",
    "Papyrus' date didn't go well, did it? Yeah, He only loves every bone in your body....",
    "Everytime I hear a skeleton joke I feel it in my bones",
    "Skulls are always single because they have no body",
    "Man, these jokes aren't even that humerus.",
    "These jokes are very bare bones",
    "Oh hey, you know that Papyrus once had a dream about his car bed. You could say it was a very AUTO-BODY Experience.",
    "My brother rides a motorcycle now! He's bad to the BONE.",
    "Why do skeletons make bad miners? Because they only go 6 FOOT UNDER GROUND",
    "You wanna know why skeletons are terrible liars? Everyone can see right through them!",
    "What's Papyrus's favorite music video? Spooky Scary Skeletons!",
    "Did ya hear the one about the baby skeleton? He liked to rattle his bones.",
    "A dog stole a skeleton's left leg and left arm the other day. But it's cool he's ALL RIGHT now!",
    "A dog stole a skeleton's left leg and left arm the other day. But it's cool he's ALL RIGHT now!",
    "What d'ye call a monkey with no skin? A babBONE!",
    "I don't know if I should put a little more BACKBONE into these jokes, but then again it is TIBIA expected that I'll get lazy and not try as hard to make a skele-TON of them... Dang... I'm such a BONEHEAD.",
    "I asked my brother the instrument one and he replied 'Bonegos'.",
    "The dancing Sans seem to really be in skele-tune with the music.",
    "What happens with a skeleton on e621? He gets a boner!",

    "if a black guy and a jew jumped off a building who will hit the ground first?.... the black guy because chains are heavier than ash",
    "What happens with a skeleton on e621? He gets a boner!",

    "if a black guy and a jew jumped off a building who will hit the ground first?.... the black guy because chains are heavier than ash",
    "What happens with a skeleton on e621? He gets a boner!",
];


let wrapper = document.getElementById("w");


for (let i = 0; i < Craziness.length; i++) {
    wrapper.innerHTML += `<p class="text">${Craziness[i]}</p>`;
    wrapper.style.gap = `280px`;
}


function FunctionOfCraziness() {
    
    function I_LIke_to_move_it() {
        let randomX = Math.random() * (document.body.scrollWidth - window.innerWidth);
        let randomY = Math.random() * (document.body.scrollHeight - window.innerHeight);
        window.scrollTo({
            left: randomX,
            top:randomY,
            behavior: "smooth" 
        });
    }
    
    let CrazyScroller = setInterval(I_LIke_to_move_it,500);
    
    setTimeout(() => {
        clearInterval(CrazyScroller);
            let MyText = document.getElementsByClassName("text");
    
        function Bomb() {
            for(let i = 0 ; i < MyText.length ; i++){
                let randomX = Math.random() * (document.body.scrollWidth - window.innerWidth);
                let randomY = Math.random() * (document.body.scrollHeight - window.innerHeight);
                window.scrollTo({
                    left: randomX,
                    top:randomY,
                    behavior: "smooth" 
                });
                MyText[i].style.animation = `Bomb 5s 1, movex 2s 1 5.5s`;
            }
    
        }
        let CrazyBomb = setInterval(Bomb,900)
    
        setTimeout(()=>{
            clearInterval(CrazyBomb);
            for (let i = 0; i < MyText.length; i++) {
                MyText[i].style.scale = `1.3 1.3`;
            }
            let CrazyBomb2 = setInterval(Bomb,500)
            setTimeout(()=>{
                clearInterval(CrazyBomb2);
            },5000)
        },5000)
      }, 5000)
}


let CrazinessVariable = setInterval(FunctionOfCraziness,500)


setTimeout(()=>{
    clearInterval(CrazinessVariable);
},308000)